# Generated by Django 4.2.5 on 2023-10-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact_model_rename_user_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadProducts_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('ImageUrl', models.CharField(max_length=1000)),
            ],
        ),
    ]
