# Generated by Django 4.2.5 on 2023-10-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uploadproducts_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproducts_model',
            name='Catagory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproducts_model',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproducts_model',
            name='ImageUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproducts_model',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
