# Generated by Django 4.2.5 on 2023-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uploadproducts_model_catagory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproducts_model',
            name='AdditionalFeatures',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='uploadproducts_model',
            name='Specifications',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
